source "https://rubygems.org"

# Debugging
gem "byebug", "~> 5.0.0"

gem "mysql2", "~> 0.3.18"
gem "pg", "~> 0.18.2"
gem "rspec", "~> 3.3.0"

# Format results for Jenkins
gem "rspec_junit_formatter", "~> 0.2.3"
